USE ROLE SYSADMIN;

GRANT CREATE DATABASE ON ACCOUNT TO ROLE DEV_SYSADMIN;

GRANT CREATE WAREHOUSE ON ACCOUNT TO ROLE DEV_SYSADMIN;

USE ROLE DEV_SYSADMIN;

CREATE DATABASE IF NOT EXISTS DEV_DPAAS_DB;

USE ROLE SYSADMIN;